default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: joe
  password: secret
  host: localhost

development:
  <<: *default
  database: skaxis_development

test:
  <<: *default
  database: skaxis_test

production:
  <<: *default
  database: <%= ENV['SKAXIS_DATABASE'] %>
  username: <%= ENV['SKAXIS_USERNAME'] %>rubyhead
  password: <%= ENV['SKAXIS_DATABASE_PASSWORD'] %>
  host: <%= ENV['SKAXIS_DATABASE_HOST'] %>
